In [1]:
import pandas as pd
import numpy as np

In [2]:
pd.__version__

'3.0.3'

In [3]:
df = pd.read_csv('car_fuel_efficiency_2026.csv')
df.head()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0

In [4]:
df.info

<bound method DataFrame.info of       model_year  origin fuel_type         drivetrain  num_doors  \
0           2006  Europe  Gasoline  Front-wheel drive          4
1           2008  Europe    Diesel  Front-wheel drive          4
2           1996    Asia  Gasoline  Front-wheel drive          5
3           1989  Europe  Gasoline  Front-wheel drive          4
4           1994     USA    Diesel  Front-wheel drive          3
...          ...     ...       ...                ...        ...
9995        2005     USA  Gasoline    All-wheel drive          4
9996        1993    Asia  Gasoline    All-wheel drive          2
9997        2014     USA  Gasoline    All-wheel drive          3
9998        2004     USA    Hybrid   Rear-wheel drive          5
9999        2011     USA    Diesel  Front-wheel drive          4

      engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                    2180              6       243.0            3870
1                    2390              6       272.0            4210
2                    2320              6       267.0            4240
3                    2130              6       258.0            4490
4                    2580              7       304.0            4510
...                   ...            ...         ...             ...
9995                 2470              6       271.0            4690
9996                 2300              6       244.0            4370
9997                 2480              6       267.0            4590
9998                 2180              6       270.0            4450
9999                 2380              6       295.0            4370

      acceleration  fuel_efficiency_mpg
0              NaN                 31.9
1              NaN                 31.3
2             17.3                 27.5
3             18.7                 28.5
4             17.5                 31.0
...            ...                  ...
9995          18.9                 27.4
9996          19.0                 30.0
9997          18.4                 28.1
9998          20.9                 32.2
9999          17.6                 30.2

[10000 rows x 11 columns]>

In [5]:
df['fuel_type'].nunique()

3

In [6]:
df.isnull().sum()

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower             877
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64

In [7]:
df[df['origin'] == 'Asia']['fuel_efficiency_mpg'].max()

np.float64(41.2)

In [8]:
df['horsepower'].mean()

np.float64(254.44601556505535)

In [9]:
df['horsepower'] = df['horsepower'].fillna(df['horsepower'].mode()[0])
df['horsepower'].mean()

np.float64(254.2315)

In [10]:
df['horsepower'].mode()

0    252.0
Name: horsepower, dtype: float64

In [11]:
df[df['origin'] == 'Asia'][['vehicle_weight','model_year']][:7]

    vehicle_weight  model_year
2             4240        1996
6             4310        1992
8             4230        1997
10            4420        1978
15            3950        2007
16            4750        2021
22            4450        2019

In [12]:
X = df[df['origin'] == 'Asia'][['vehicle_weight','model_year']][:7].to_numpy()
X, X.T

(array([[4240, 1996],
        [4310, 1992],
        [4230, 1997],
        [4420, 1978],
        [3950, 2007],
        [4750, 2021],
        [4450, 2019]]),
 array([[4240, 4310, 4230, 4420, 3950, 4750, 4450],
        [1996, 1992, 1997, 1978, 2007, 2021, 2019]]))

In [13]:
XTX = X.T @ X
XTX

array([[131950500,  60750580],
       [ 60750580,  28041424]])

In [14]:
XTX = np.linalg.inv(XTX)
XTX

array([[ 2.96830537e-06, -6.43071025e-06],
       [-6.43071025e-06,  1.39675281e-05]])

In [15]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])
y

array([1100, 1300,  800,  900, 1000, 1100, 1200])

In [16]:
w = (XTX @ X.T) @ y
w

array([0.13644777, 0.2327492 ])

In [17]:
np.sum(w)

np.float64(0.36919696904927746)